openapi: 3.0.2
info:
  title: Metrics API
  version: 1.0.0
paths:
  /metrics:
    post:
      summary: Add new metrics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: Name of the metric
                    example: cpu_usage
                  value:
                    type: number
                    description: Value of the metric
                    example: 0.75
      responses:
        '201':
          description: Metrics added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Metrics added successfully
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Expected a list of metrics
  /metrics/average:
    get:
      summary: Get average of metrics
      parameters:
        - in: query
          name: start
          required: true
          schema:
            type: string
            format: date-time
          description: Start date
        - in: query
          name: end
          required: true
          schema:
            type: string
            format: date-time
          description: End date
        - in: query
          name: granularity
          required: true
          schema:
            type: string
            enum: [minutes, hours, days]
          description: Granularity of the average
        - in: query
          name: name
          required: true
          schema:
            type: array
            items:
              type: string
          description: Names of the metrics
      responses:
        '200':
          description: Average metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  averages:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the metric
                          example: cpu_usage
                        timestamp:
                          type: string
                          format: date-time
                          description: Timestamp of the average
                          example: '2023-01-01T00:00:00Z'
                        average:
                          type: number
                          description: Average value of the metric
                          example: 0.75
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Missing start or end parameter
  /metrics/list:
    get:
      summary: List all available metrics
      responses:
        '200':
          description: List of metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  metrics:
                    type: array
                    items:
                      type: string
                      description: List of metric names
                      example: cpu_usage
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
components:
  schemas:
    Metric:
      type: object
      properties:
        name:
          type: string
          description: Name of the metric
          example: cpu_usage
        value:
          type: number
          description: Value of the metric
          example: 0.75
    MetricList:
      type: object
      properties:
        metrics:
          type: array
          items:
            type: string
          description: List of metric names
    MetricAverage:
      type: object
      properties:
        name:
          type: string
          description: Name of the metric
          example: cpu_usage
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the average
          example: '2023-01-01T00:00:00Z'
        average:
          type: number
          description: Average value of the metric
          example: 0.75
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Expected a list of metrics
